
1. libuv
2. c++ wrappers
3. EventEmitter interface

- Frontend API uses listener pattern with similar events as node.js
    - native::
- C++ wrappers around libuv use continuation passing style
    - native::detail::
